# -*- coding: utf-8 -*-
"""Essay Writing AI Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pO6iFwVLTCFKs_cbTiVxQUD28n1rHbWU

# 1. LLM - Generate key terms
"""

# Install required libraries
import os
from typing import TypedDict
from dotenv import load_dotenv

# Imports
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import StateGraph, END

# 🔐 Load Groq API Key from env file
load_dotenv()

api_key = os.getenv("GROQ_API_KEY")
if not api_key:
    raise ValueError("GROQ_API_KEY not found in environment variables. Please set it in your .env file.")

os.environ["GROQ_API_KEY"] = api_key

# 🧠 Initialize LLM
llm = ChatGroq(model="llama-3.3-70b-versatile")

# 🧾 Define State
class AgentState(TypedDict):
    topic: str
    key_terms: str
    search_results: str
    draft: str
    review: str
    final_essay: str

# 🪄 Prompt for key term generation
prompt = ChatPromptTemplate.from_messages([
    ("system", """You are an expert research assistant specialized in information retrieval and topic decomposition.

Your job is to break down a given topic into high-quality key terms that will be used for web search.

Guidelines:
- Generate diverse and comprehensive key terms
- Include:
  • core concepts
  • subtopics
  • related technical terms
  • real-world applications
  • opposing viewpoints (if applicable)
- Prefer specific and descriptive phrases over generic words
- Avoid repetition
- Cover different dimensions of the topic (technical, social, economic, ethical, etc.)
- Include both short keywords and 2–4 word search phrases

Output format:
- Return ONLY a clean comma-separated list
- No explanations
- No numbering
- No extra text"""),

    ("human", "Topic: {topic}")
])

# ⚙️ Step 1 Node
def generate_key_terms(state: AgentState):
    chain = prompt | llm
    response = chain.invoke({"topic": state["topic"]})

    return {
        "key_terms": response.content.strip()
    }

"""# 2. Tool - Web Search Tool"""

# 1. INSTALL SEARCH DEPENDENCY

from langchain_community.tools import DuckDuckGoSearchRun

# Initialize the search tool
search_tool = DuckDuckGoSearchRun()


# 2. STEP 2: SEARCH NODE
def research_topics(state: AgentState):
    print("\n--- RESEARCHING KEY TERMS ---")

    all_results = []

    terms = [t.strip() for t in state["key_terms"].split(",")]

    for term in terms[:5]:
        query = f"{state['topic']} {term}"

        print(f"Searching for: {query}...")

        try:
            result = search_tool.run(query)
            cleaned = result[:800]
            all_results.append(f"Insight ({term}):\n{cleaned}")

        except Exception as e:
            all_results.append(f"{term}: Failed ({e})")

    # Combine all search snippets into one string
    combined_info = "\n\n---\n\n".join(all_results)
    if not combined_info.strip():
        combined_info = "Limited research data available. Write based on general knowledge."
    combined_info = combined_info[:3000]

    return {
        "search_results": combined_info
    }


"""# 3. LLM - First Draft"""

# STEP 3: DRAFTER NODE (FINAL)
def write_first_draft(state: AgentState):
    print("\n--- WRITING FIRST DRAFT ---")

    drafter_prompt = ChatPromptTemplate.from_messages([

        ("system", """You are an expert academic essay writer known for clarity, depth, and natural flow.

Your task is to write a high-quality, human-like essay based on provided research.

Writing Guidelines:
- Begin with an engaging introduction that clearly presents the topic and a strong thesis statement
- Develop 3–5 well-structured body paragraphs
- Each paragraph should focus on one main idea and build logically on the previous one
- Use smooth transitions to ensure a natural flow throughout the essay
- Integrate research insights naturally into the writing (do NOT copy, list, or dump information)
- Explain ideas clearly with reasoning, not just facts
- Maintain a formal yet engaging tone
- Avoid repetition, vague statements, and generic phrasing
- Ensure coherence, depth, and readability

Conclusion:
- End with a thoughtful conclusion that reinforces the main argument and provides a broader insight

Important Constraints:
- Do NOT use bullet points or lists
- Do NOT include headings like "Introduction" or "Conclusion"
- Do NOT mention "research data" or sources explicitly
- The essay should read as if written by a skilled human writer

Output:
Return ONLY the final essay text."""),

        ("human", """Topic: {topic}

Research Data:
{research_results}

Write the first draft of the essay.""")
    ])

    chain = drafter_prompt | llm

    response = chain.invoke({
        "topic": state["topic"],
        "research_results": state["search_results"]
    })

    return {
        "draft": response.content.strip()
    }



"""# 4. LLM - Review Draft 1"""

# STEP 4: REVIEWER NODE

def review_draft(state: AgentState):
    print("\n--- REVIEWING DRAFT ---")

    reviewer_prompt = ChatPromptTemplate.from_messages([

        ("system", """You are a highly critical academic reviewer and writing expert.

Your task is to evaluate an essay draft and provide detailed, constructive feedback.

Evaluation Criteria:
- Clarity and coherence
- Logical flow between paragraphs
- Strength of arguments and reasoning
- Depth of explanation
- Use of ideas (not just surface-level writing)
- Engagement and readability
- Grammar and style

Instructions:
- Be honest and critical (do NOT sugarcoat)
- Identify weaknesses clearly
- Suggest specific improvements
- Point out missing depth or weak arguments
- Recommend how to improve flow and structure

Output Format:

Strengths:
- ...

Weaknesses:
- ...

Improvements:
- ...

Do NOT rewrite the essay.
ONLY provide feedback."""),

        ("human", """Topic: {topic}

Essay Draft:
{draft}

Review this draft.""")
    ])

    chain = reviewer_prompt | llm

    response = chain.invoke({
        "topic": state["topic"],
        "draft": state["draft"]
    })

    return {
        "review": response.content.strip()
    }


"""# 5. LLM - Write Final Draft"""

def rewrite_essay(state: AgentState):
    print("\n--- REWRITING FINAL ESSAY ---")

    rewriter_prompt = ChatPromptTemplate.from_messages([

        ("system", """You are an expert academic writer and editor.

Your task is to improve an essay using detailed review feedback.

Instructions:
- Carefully analyze the feedback and fix ALL weaknesses
- Improve clarity, depth, and logical flow
- Strengthen arguments and explanations
- Ensure smooth transitions between paragraphs
- Maintain a formal yet engaging tone
- Remove vague or repetitive statements
- Make the essay more polished and impactful

Important:
- Do NOT mention the review or feedback
- Do NOT include bullet points or headings
- The output should be a clean, final essay
- It should feel like a refined, high-quality human-written piece

Output:
Return ONLY the final improved essay"""),

        ("human", """Topic: {topic}

Original Draft:
{draft}

Review Feedback:
{review}

Rewrite the essay into a final polished version.""")
    ])

    chain = rewriter_prompt | llm

    response = chain.invoke({
        "topic": state["topic"],
        "draft": state["draft"],
        "review": state["review"]
    })

    return {
        "final_essay": response.content.strip()
    }


"""# Final Graph Compilation"""
workflow = StateGraph(AgentState)

workflow.add_node("planner", generate_key_terms)
workflow.add_node("researcher", research_topics)
workflow.add_node("drafter", write_first_draft)
workflow.add_node("reviewer", review_draft)
workflow.add_node("rewriter", rewrite_essay)

workflow.set_entry_point("planner")

workflow.add_edge("planner", "researcher")
workflow.add_edge("researcher", "drafter")
workflow.add_edge("drafter", "reviewer")
workflow.add_edge("reviewer", "rewriter")
workflow.add_edge("rewriter", END)

app = workflow.compile()



"""# Final Run for Sample Topic"""

def run_agent(topic: str):
    return app.invoke({"topic": topic})

# The impact of Artificial Intelligence on modern healthcare